
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.url=jdbc:mysql://100.119.92.93:3306/global_finance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=leninrevan
db.password=Starnooki
